# Generated by Django 3.2.3 on 2021-05-16 04:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='input',
            name='category',
            field=models.CharField(default='inverse', max_length=30),
        ),
    ]
