# Generated by Django 3.2.3 on 2021-05-16 04:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20210516_0422'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='api_key',
            field=models.TextField(unique=True),
        ),
        migrations.AlterField(
            model_name='account',
            name='secret_key',
            field=models.TextField(unique=True),
        ),
    ]
