# Generated by Django 3.2.3 on 2021-05-16 04:54

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_auto_20210516_0433'),
    ]

    operations = [
        migrations.AlterField(
            model_name='input',
            name='end_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 5, 16, 4, 54, 50, 200014)),
        ),
    ]
