# Generated by Django 3.2.3 on 2021-05-16 04:55

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_alter_input_end_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='input',
            name='account',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='main.account'),
        ),
        migrations.AlterField(
            model_name='input',
            name='end_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 5, 16, 4, 55, 38, 629225)),
        ),
    ]
