# Generated by Django 3.2.3 on 2021-05-16 04:56

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_auto_20210516_0455'),
    ]

    operations = [
        migrations.AlterField(
            model_name='input',
            name='end_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
