# Generated by Django 3.2.3 on 2021-05-16 05:02

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):
    dependencies = [
        ('main', '0007_alter_input_end_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='input',
            name='Currency',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.currency'),
            preserve_default=False,
        ),
    ]
