# Generated by Django 3.2.3 on 2021-05-16 05:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_input_currency'),
    ]

    operations = [
        migrations.CreateModel(
            name='RecordedData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('before', models.CharField(max_length=60)),
                ('amount', models.CharField(max_length=60)),
                ('after', models.CharField(max_length=60)),
                ('ledger_id', models.CharField(max_length=60)),
                ('realised_pnl', models.CharField(max_length=60)),
                ('captured_date', models.DateTimeField()),
                ('Input', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.input')),
            ],
        ),
    ]
