# Generated by Django 3.2.3 on 2021-05-16 06:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_rename_currency_input_currency'),
    ]

    operations = [
        migrations.AddField(
            model_name='recordeddata',
            name='type',
            field=models.CharField(default='', max_length=30),
        ),
    ]
