# Generated by Django 3.2.3 on 2021-05-19 19:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_recordeddata_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='Exchange',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=60, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='input',
            name='exchange',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='main.exchange'),
            preserve_default=False,
        ),
    ]
