# Generated by Django 3.2.3 on 2021-05-19 19:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_auto_20210519_1914'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='currency',
            name='short_code',
        ),
    ]
