# Generated by Django 3.2.3 on 2021-05-19 20:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_remove_currency_short_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='recordeddata',
            name='roi',
            field=models.CharField(default='', max_length=60),
            preserve_default=False,
        ),
    ]
