# Generated by Django 3.2.3 on 2021-05-20 05:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0015_log'),
    ]

    operations = [
        migrations.AlterField(
            model_name='log',
            name='input',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.input'),
        ),
    ]
