# Generated by Django 3.2.3 on 2021-05-20 15:50

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0016_alter_log_input'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='log',
            name='input',
        ),
        migrations.AddField(
            model_name='log',
            name='category',
            field=models.CharField(default='inverse', max_length=30),
        ),
        migrations.AddField(
            model_name='log',
            name='currency',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main.currency'),
        ),
        migrations.AddField(
            model_name='log',
            name='end_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='log',
            name='exchange',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main.exchange'),
        ),
        migrations.AddField(
            model_name='log',
            name='start_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
