# Generated by Django 3.2.3 on 2021-05-20 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0017_auto_20210520_1550'),
    ]

    operations = [
        migrations.AddField(
            model_name='log',
            name='input_id',
            field=models.IntegerField(default=2),
            preserve_default=False,
        ),
    ]
